[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "bash"
file-types = [
  "sh",
  { glob = "*zshrc*" },
  { glob = "*bashrc*" }
]

[[language]]
name = "toml"
file-types = [
  "toml",
  { glob = "*.toml.tmpl" }
]

[[language]]
name = "json"
file-types = [
  "json",
  { glob = "*.json.tmpl" }
]
